### ISSUE TITLE
Using `kubectl delete` to remove Razee results in removing `cluster-admin` ClusterRole

### ISSUE THREAD

**Issue by jpapejr** [razee-io/Razee#15]
## What happpened
When trying to remove Razee from a cluster, I used `kubectl delete -f https://github.com/razee-io/Kapitan-delta/releases/latest/download/resource.yaml` to begin removing resources. After the command completes, the `cluster-admin` role binding has been removed from my cluster. The result is that my standard user `IAM#jtpape@us.ibm.com` cannot access everything in the cluster per my IAM privs as account owner. 

## How I fixed the problem
Since I'm using IKS, I can re-export my kubeconfig files using `ibmcloud ks cluster-config <mycluster> --export --admin` and restore access to my cluster by applying the following YAML to the cluster. 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

## What I expected to happen
When using `kubectl delete`, I didn't expect to lose the built in `cluster-admin` ClusterRole that IKS provides me.
