### ISSUE TITLE
RemoteResource headers to allow secretKeyRef

### ISSUE THREAD

**Issue by maire-kehoe** [razee-io/Razee#53]
My use-case is, I have a private GitHub.com repo, and I can use my personal-access-token in the Authorization header to read the content of a file in the private repo through the api. However I would like to put my access token in a secret resource, but it doesn't seem to be supported.

The documentation for RemoteResource doesn't mention any ability to use secretKeyRef in the headers - it would be good if that or some similar syntax could be supported. 

That is, this works ok (when I insert my access token):
```
apiVersion: kapitan.razee.io/v1alpha1
kind: RemoteResource
metadata:
  name: hello-remote
spec:
  requests:
  - options:
      url: https://api.github.com/repos/maire-kehoe/test-razee-private/contents/helloConfigMap.yml?ref=master
      headers:
        Authorization: token <my-personal-access-token>
        Accept: application/vnd.github.VERSION.raw
        User-Agent: cluster-remoteresource-yml-github-agent
```

But this doesn't work:
```
apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: kubernetes.io/basic-auth
stringData:
  password: token <my-personal-access-token>
---
apiVersion: kapitan.razee.io/v1alpha1
kind: RemoteResource
metadata:
  name: hello-remote
spec:
  requests:
  - options:
      url: https://api.github.com/repos/maire-kehoe/test-razee-private/contents/helloConfigMap.yml?ref=master
      headers:
        Authorization:
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: password
        Accept: application/vnd.github.VERSION.raw
        User-Agent: cluster-remoteresource-yml-github-agent
```

At present, the hello-remote resource is created, but the referenced config map is not created, and the `kubectl describe rr hello-remote` contains this status:
```
Status:
  Fatal:
    Status Code:  404
    Uri:          https://api.github.com/repos/maire-kehoe/test-razee-private/contents/helloConfigMap.yml?ref=master
```
that is, there's a 404 not found error because the Authorization value was not sent to the api.github.com (and they return 404 Not Found instead of 401 Unauthorized to avoid leaking file-existence info to unauthorized requests.)
