### ISSUE TITLE
When using the `Install Razee Agent` command line from app.razee.io - watch-keeper is never installed

### ISSUE THREAD

**Issue by jpapejr** [razee-io/Razee#62]
**Describe the bug**
Watch-keeper never gets started in a new install because the YAML downloaded from the agent install endpoint uses the wrong apiGroup for the RemoteResource type. Provided yaml: 

```
apiVersion: "kapitan.razee.io/v1alpha1"
kind: RemoteResource
metadata:
  name: watch-keeper-rr
  namespace: razee
spec:
  requests:
    - options:
        url: https://github.com/razee-io/watch-keeper/releases/latest/download/resource.yaml
```

Correct value would be 

```
apiVersion: "deploy.razee.io/v1alpha1"
kind: RemoteResource
metadata:
  name: watch-keeper-rr
  namespace: razee
spec:
  requests:
    - options:
        url: https://github.com/razee-io/watch-keeper/releases/latest/download/resource.yaml
```

**To Reproduce**
1. Go to app.razee.io and register a github org
2. Click on Manage for that new org after authorization is done
3. Copy the agent install command line and apply on target cluster.
4. Note that watch-keeper pods aren't started and there's an error complaining about the RemoteResource type in the `kapitan.razee.io/v1alpha1` type. 

**Expected behavior**
Watch-keeper pods should show up and start running in my cluster. 

**Screenshots**
n/a

**Kubernetes Version (kubectl version):**
 - Client: 1.14.0
 - Server: 1.14.0 IKS

**Additional context**
n/a
