### ISSUE TITLE
When using automated deployment from a GHE repo, the yaml being deployed needs to be deployed to the cluster before automated deployment will work

### ISSUE THREAD

**Issue by NellaFej** [razee-io/Razee#94]
**Describe the bug**
When using automated deployment from a GHE repo, the yaml being deployed needs to be deployed to the cluster before automated deployment will work.

I have seen this several times.  I install the remote resource and have a logs - f of the remotresource-controller pod.  I watch the scheduler (it runs every 5 minutes and should be configurable, if it is I cannot find that configuration).  I see a 404 error when the controller runs saying that the file designated in the RR is not found.  I curl the same url with my token and it returns the file content.  So I deploy the file manually and the next scheduled run says all is fine with that file - it exists and there are no changes.  I update th efile and the update gets deployed by the RR
**To Reproduce**

**Expected behavior**
I would expect that any file in the rr would get deployed.  I have added my rr itself to the rr, this way if I add files to that rr it should redeploy itself and pick up those new files
**Screenshots**

**Kubernetes Version (kubectl version):**
 - Client: 
 - Server:
[jagaber@oc3715088365 razee-demo]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2020-01-14T00:28:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by alewitt2** [comment]
im not sure i follow what your issue is? can you give some examples of what your files and remoteresource looks like so that i may try to reproduce?

fyi: the scheduler timer is configurable via: (the default is 300 seconds)
```
              - name: CRD_WATCH_TIMEOUT_SECONDS
                valueFrom:
                  configMapKeyRef:
                    name: razeedeploy-overrides
                    key: CRD_WATCH_TIMEOUT_SECONDS
                    optional: true
```

**Comment by NellaFej** [comment]
The issue is not with the watch time, the issue is that when there is no deploy resource the rr will not deploy the resource.  When I manually deploy the resource, then make a change to the resource and commit that change back to github, then the rr will pick up the change.

So I have a namespace with nothing in it.  I deploy a remoteresource that points to some deploy.yaml in github.  I make a change to that deploy.yaml.  It does not pick  up the yaml.  If I manually deploy that yaml, then make a change to the yaml it picks up the changed yaml.

I think when the remote resource first starts it should run the process to pull its requests, if the yaml was already installed the resources will be unchanged.

If this is the way it is designed currently, I see it not working that way.

**Comment by alewitt2** [comment]
can you show me an example of what your RR looks like?

**Comment by alewitt2** [comment]
just to make sure im clear on whats going on..

1. you have a cluster with an empty namespace, something like `newnamespace`
1. you have a yaml in github, something like
    ```
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-configmap
      namespace: newnamespace
    data:
      testing: 'one-two-three'
    ```
1. you deploy a remote resource to your `newnamespace` namespace with a url to this configmap yaml
    ```
    apiVersion: deploy.razee.io/v1alpha2
    kind: RemoteResource
    metadata:
      name: test-remoteresource
      namespace: newnamespace
    spec:
      requests:
        - options:
            url: https://github.com/yourfilesomewhere/test-configmap.yaml
    ```
1. your configmap is deployed successfully
1. you edit the yaml in github, something like
    ```
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-configmap
      namespace: newnamespace
    data:
      testing: 'one-two-three'
      testing-again: 'four-five-six'
    ```
1. the changed yaml doesnt show up on your cluster?
1. you manually apply the updated configmap yaml (how do you do this manual apply? by url or by local file?)
1. now the remoteresource starts applying the correct yaml?
