### ISSUE TITLE
Razee Uninstall causes resources to be removed from kubernetes

### ISSUE THREAD

**Issue by zach-source** [razee-io/Razee#99]
**Is your feature request related to a problem? Please describe.**
Uninstalling the CR and CRDs removes the resources in the remote resources files. If we add a URL row, we'd like for that yaml to remain after we remove the child resource.

**Describe the solution you'd like**
We'd like to be able to delete the child resource and have the resources remain.

**Describe alternatives you've considered**
We've attempted to use the Reconcile=false flag, we don't think this necessarily works for our use case.

**Additional context**
Use case steps;
1. Add row to child resource with url.
2. URL yaml is applied to kubernetes.
3. Uninstall razee (via job or delete crds, controllers, etc).
4. Expect to see the resource from YAML still on the system.

**Comment by cherylfbrown** [comment]
Here's an example of the remoteresource we are using, which we call child:

```
apiVersion: deploy.razee.io/v1alpha2
kind: RemoteResourceS3
metadata:
  name: child
  namespace: openshift-redhat-marketplace
spec:
  auth:
    iam:
      responseType: cloud_iam
      grantType: "urn:ibm:params:oauth:grant-type:apikey"
      url: "https://iam.cloud.ibm.com/identity/token"
      apiKeyRef:
        valueFrom:
          secretKeyRef:
            name: rhm-cos-reader-key
            key: accesskey
  requests:
    - options:
        url: "https://s3.us-east.cloud-object-storage.appdomain.cloud/1234-dev/asdf/operatorsource.yaml"
    - options:
        url: "https://s3.us-east.cloud-object-storage.appdomain.cloud/1234-dev/asdf/subscriptions/hazelcast-enterprise-certified-rhmp-ns-test-1.yaml"
    - options:
        url: "https://s3.us-east.cloud-object-storage.appdomain.cloud/1234-dev/asdf/subscriptions/cockroachdb-certified-rhmp-ns-test-1.yaml"
```

**Comment by alewitt2** [comment]
> We've attempted to use the Reconcile=false flag, we don't think this necessarily works for our use case.

can you elaborate on this? the Reconcile label is meant to do exactly what you are describing. Please note, the resource in your example called `child` is actually what i would consider the parent, where all the yaml that is created from the urls defined in your `child` remote resource, i would consider the children. eg. you should put the reconcile label on all of the urls yaml (what i consider the children) that you want to stay on the cluster.

**Comment by zach-source** [comment]
Ah, hang on Alex. Can you provide a clear example of what a child and parent is to you and where it exists? We have a resource created on kubernetes with information to connect to S3. It then pulls down the RSS3 with the urls. Which of these does the reconcile flag affect and which should it be applied to?

**Comment by cherylfbrown** [comment]
Yeah we have a parent that points to the child above, which ultimately points to the items we want to apply to the cluster (grandchildren?).

Here's what the parent looks like fyi (output from oc describe):
```
apiVersion: deploy.razee.io/v1alpha2
kind: RemoteResourceS3
metadata:
  annotations:
    deploy.razee.io/data-hash: f059b541628b08eaf39986a07d2bc44d7d4c5de2
  creationTimestamp: "2020-04-27T15:10:00Z"
  finalizers:
  - children.downloads.deploy.razee.io
  generation: 1
  name: parent
  namespace: openshift-redhat-marketplace
  resourceVersion: "488753"
  selfLink: /apis/deploy.razee.io/v1alpha2/namespaces/openshift-redhat-marketplace/remoteresourcess3/parent
  uid: 59f54fcb-a58d-4b04-bbc6-bc9fe6e93b52
spec:
  auth:
    iam:
      apiKeyRef:
        valueFrom:
          secretKeyRef:
            key: accesskey
            name: rhm-cos-reader-key
      grantType: urn:ibm:params:oauth:grant-type:apikey
      responseType: cloud_iam
      url: https://iam.cloud.ibm.com/identity/token
  requests:
  - options:
      url: https://s3.us-east.cloud-object-storage.appdomain.cloud/1234-dev/asdf/childRRS3.yaml
```

**Comment by alewitt2** [comment]
sure. so the reconcile label can either be placed on the remoteresource itself, or the yamls that the RR creates. When you put it on the RR itself, it sets the default behavior for the resources it creates. Setting the labels on the resources directly gives you the finest control..

for example, if i want my deployment to not be cleaned up by my RemoteResourceS3, i would add the reconcile false label to it:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    deploy.razee.io/Reconcile: false
spec:
...
```

if you dont want to add the `deploy.razee.io/Reconcile=false` label to all of your resources, you can put it on your RR and it will change the default of `true` to `false` (unless of course the child specifies otherwise)..

```
apiVersion: deploy.razee.io/v1alpha2
kind: RemoteResourceS3
metadata:
  name: child
  namespace: openshift-redhat-marketplace
  labels:
    deploy.razee.io/Reconcile: "false"
spec:
  auth:
    iam:
      responseType: cloud_iam
      grantType: "urn:ibm:params:oauth:grant-type:apikey"
      url: "https://iam.cloud.ibm.com/identity/token"
      apiKeyRef:
        valueFrom:
          secretKeyRef:
            name: rhm-cos-reader-key
            key: accesskey
  requests:
    - options:
        url: "https://s3.us-east.cloud-object-storage.appdomain.cloud/1234-dev/asdf/operatorsource.yaml"
    - options:
        url: "https://s3.us-east.cloud-object-storage.appdomain.cloud/1234-dev/asdf/subscriptions/hazelcast-enterprise-certified-rhmp-ns-test-1.yaml"
    - options:
        url: "https://s3.us-east.cloud-object-storage.appdomain.cloud/1234-dev/asdf/subscriptions/cockroachdb-certified-rhmp-ns-test-1.yaml"
```

Note: the changing of the default behavior for the children only works one level deep, in your example, if you set the `deploy.razee.io/Reconcile: false` label at the very top level, its grandchild would still be `deploy.razee.io/Reconcile: true`
